//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeekiosApp.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeekiosApp.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à This email already exists, it&apos;s possible that you already have an account..
        /// </summary>
        internal static string AccountAlreadyExistsText {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Existing account.
        /// </summary>
        internal static string AccountAlreadyExistsTitle {
            get {
                return ResourceManager.GetString("AccountAlreadyExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added {0}d at {1}.
        /// </summary>
        internal static string AddedSinceAt {
            get {
                return ResourceManager.GetString("AddedSinceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added today at {0}.
        /// </summary>
        internal static string AddedTodayAt {
            get {
                return ResourceManager.GetString("AddedTodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Added yesterday at {0}.
        /// </summary>
        internal static string AddedYesterdayAt {
            get {
                return ResourceManager.GetString("AddedYesterdayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à It seems this seekios is already being used.
        /// </summary>
        internal static string AddSeekiosAlreadyUsed {
            get {
                return ResourceManager.GetString("AddSeekiosAlreadyUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Wrong PIN or IMEI. Try again. If the problem persists, contact the support.
        /// </summary>
        internal static string AddSeekiosIMEIOrPinError {
            get {
                return ResourceManager.GetString("AddSeekiosIMEIOrPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding seekios.
        /// </summary>
        internal static string AddSeekiosTitle {
            get {
                return ResourceManager.GetString("AddSeekiosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must define an alert content.
        /// </summary>
        internal static string AlertActivity_MissingContent_Content {
            get {
                return ResourceManager.GetString("AlertActivity_MissingContent_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty content.
        /// </summary>
        internal static string AlertActivity_MissingContent_Title {
            get {
                return ResourceManager.GetString("AlertActivity_MissingContent_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must define at least one recipient.
        /// </summary>
        internal static string AlertActivity_MissingRecipientContent {
            get {
                return ResourceManager.GetString("AlertActivity_MissingRecipientContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Missing recipient.
        /// </summary>
        internal static string AlertActivity_MissingRecipientTitle {
            get {
                return ResourceManager.GetString("AlertActivity_MissingRecipientTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must define an email object.
        /// </summary>
        internal static string AlertActivity_MissingTitle_Content {
            get {
                return ResourceManager.GetString("AlertActivity_MissingTitle_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty email address.
        /// </summary>
        internal static string AlertActivity_MissingTitle_Title {
            get {
                return ResourceManager.GetString("AlertActivity_MissingTitle_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alert error.
        /// </summary>
        internal static string AlertErrorTitle {
            get {
                return ResourceManager.GetString("AlertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You need to update your application.
        /// </summary>
        internal static string AppNeedsUpdate {
            get {
                return ResourceManager.GetString("AppNeedsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Version error.
        /// </summary>
        internal static string AppNeedsUpdateTitle {
            get {
                return ResourceManager.GetString("AppNeedsUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The email address and/or the password are incorrect.
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Authentication failed.
        /// </summary>
        internal static string AuthenticationFailedTitle {
            get {
                return ResourceManager.GetString("AuthenticationFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password you entered is not correct.
        /// </summary>
        internal static string BadPassword {
            get {
                return ResourceManager.GetString("BadPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bad password.
        /// </summary>
        internal static string BadPasswordTitle {
            get {
                return ResourceManager.GetString("BadPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your seekios battery has been updated.
        /// </summary>
        internal static string BatteryUpdated {
            get {
                return ResourceManager.GetString("BatteryUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Battery update.
        /// </summary>
        internal static string BatteryUpdateTitle {
            get {
                return ResourceManager.GetString("BatteryUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The mode couldn&apos;t be deleted.
        /// </summary>
        internal static string CannotDeleteModeMessage {
            get {
                return ResourceManager.GetString("CannotDeleteModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete error.
        /// </summary>
        internal static string CannotDeleteModeTitle {
            get {
                return ResourceManager.GetString("CannotDeleteModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unregistered Mode.
        /// </summary>
        internal static string CannotSaveMode {
            get {
                return ResourceManager.GetString("CannotSaveMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SOS configuration couldn&apos;t be saved.
        /// </summary>
        internal static string CannotSaveSOS {
            get {
                return ResourceManager.GetString("CannotSaveSOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One of the fields is empty, please fill it in to add this alert to favorites.
        /// </summary>
        internal static string ContentEmptyEmail {
            get {
                return ResourceManager.GetString("ContentEmptyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The SMS message field is empty, please fill it in to add this alert to your favorites.
        /// </summary>
        internal static string ContentEmptySMS {
            get {
                return ResourceManager.GetString("ContentEmptySMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We could not register your device for notifications.
        /// </summary>
        internal static string CouldNotRegisterForNotifContent {
            get {
                return ResourceManager.GetString("CouldNotRegisterForNotifContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while registering.
        /// </summary>
        internal static string CouldNotRegisterForNotifTitle {
            get {
                return ResourceManager.GetString("CouldNotRegisterForNotifTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while disconnecting.
        /// </summary>
        internal static string CouldNotUnRegisterForNotifContent {
            get {
                return ResourceManager.GetString("CouldNotUnRegisterForNotifContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not unregister from notification service.
        /// </summary>
        internal static string CouldNotUnRegisterForNotifTitle {
            get {
                return ResourceManager.GetString("CouldNotUnRegisterForNotifTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid country code.
        /// </summary>
        internal static string CountryCodeError {
            get {
                return ResourceManager.GetString("CountryCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account creation failed.
        /// </summary>
        internal static string CreateAccountFailedText {
            get {
                return ResourceManager.GetString("CreateAccountFailedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error has occurred, please try again later..
        /// </summary>
        internal static string CreateAccountFailedTitle {
            get {
                return ResourceManager.GetString("CreateAccountFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your account has been successfully created, a validation email has been sent to you.
        /// </summary>
        internal static string CreateAccountSuccessText {
            get {
                return ResourceManager.GetString("CreateAccountSuccessText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create Account Completed.
        /// </summary>
        internal static string CreateAccountSuccessTitle {
            get {
                return ResourceManager.GetString("CreateAccountSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Low battery !.
        /// </summary>
        internal static string CriticalBattery {
            get {
                return ResourceManager.GetString("CriticalBattery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete the current mode ?.
        /// </summary>
        internal static string DeleteModeContent {
            get {
                return ResourceManager.GetString("DeleteModeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string DeleteModeNo {
            get {
                return ResourceManager.GetString("DeleteModeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Look out ! Your seekios will remain in power saving. The mode will be active at the next noon: the gray icon will turn green when the mode is activated..
        /// </summary>
        internal static string DeleteModePowerSavingOnContent {
            get {
                return ResourceManager.GetString("DeleteModePowerSavingOnContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The last mode has been deleted !.
        /// </summary>
        internal static string DeleteModeSuccess {
            get {
                return ResourceManager.GetString("DeleteModeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete mode.
        /// </summary>
        internal static string DeleteModeSuccessTitle {
            get {
                return ResourceManager.GetString("DeleteModeSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes.
        /// </summary>
        internal static string DeleteModeYes {
            get {
                return ResourceManager.GetString("DeleteModeYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your seekios has been removed from your account..
        /// </summary>
        internal static string DeleteSeekiosSuccess {
            get {
                return ResourceManager.GetString("DeleteSeekiosSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete seekios.
        /// </summary>
        internal static string DeleteSeekiosTitle {
            get {
                return ResourceManager.GetString("DeleteSeekiosTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Canceling sharing.
        /// </summary>
        internal static string DeleteSharing {
            get {
                return ResourceManager.GetString("DeleteSharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to delete zone.
        /// </summary>
        internal static string DeleteZoneFailed {
            get {
                return ResourceManager.GetString("DeleteZoneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to delete zone.
        /// </summary>
        internal static string DeleteZoneFailedTitle {
            get {
                return ResourceManager.GetString("DeleteZoneFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No Seekios account is linked to the email address you entered..
        /// </summary>
        internal static string EmailDoesntExistsText {
            get {
                return ResourceManager.GetString("EmailDoesntExistsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unknown email address.
        /// </summary>
        internal static string EmailDoesntExistsTitle {
            get {
                return ResourceManager.GetString("EmailDoesntExistsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email field empty, please enter an email.
        /// </summary>
        internal static string EmailEmptyContent {
            get {
                return ResourceManager.GetString("EmailEmptyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email error.
        /// </summary>
        internal static string EmailErrorTitle {
            get {
                return ResourceManager.GetString("EmailErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email not found, check your email.
        /// </summary>
        internal static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Syntax error, verify your email.
        /// </summary>
        internal static string EmailSyntaxErrorContent {
            get {
                return ResourceManager.GetString("EmailSyntaxErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name field is empty.
        /// </summary>
        internal static string EmptyFirstName {
            get {
                return ResourceManager.GetString("EmptyFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name field is empty.
        /// </summary>
        internal static string EmptyLastName {
            get {
                return ResourceManager.GetString("EmptyLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty password.
        /// </summary>
        internal static string EmptyPassword {
            get {
                return ResourceManager.GetString("EmptyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à every {0}.
        /// </summary>
        internal static string Every {
            get {
                return ResourceManager.GetString("Every", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to connect with Facebook.
        /// </summary>
        internal static string FacebookConnectionFailedTitle {
            get {
                return ResourceManager.GetString("FacebookConnectionFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can not add this bookmark because it already exists in the list.
        /// </summary>
        internal static string FavoriteAlertAlreadyExist {
            get {
                return ResourceManager.GetString("FavoriteAlertAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Already Favorite Alert.
        /// </summary>
        internal static string FavoriteAlertAlreadyExistTitle {
            get {
                return ResourceManager.GetString("FavoriteAlertAlreadyExistTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A new password will be sent to your email address.
        /// </summary>
        internal static string ForgetPassword {
            get {
                return ResourceManager.GetString("ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Please enter your email address.
        /// </summary>
        internal static string ForgetPassword_FieldEmpty {
            get {
                return ResourceManager.GetString("ForgetPassword_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty field.
        /// </summary>
        internal static string ForgetPassword_FieldEmptyTitle {
            get {
                return ResourceManager.GetString("ForgetPassword_FieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your email address does not match any existing addresses.
        /// </summary>
        internal static string ForgetPassword_NoEmail {
            get {
                return ResourceManager.GetString("ForgetPassword_NoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input error.
        /// </summary>
        internal static string ForgetPassword_NoEmailTitle {
            get {
                return ResourceManager.GetString("ForgetPassword_NoEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm password accepted.
        /// </summary>
        internal static string ForgetPasswordTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMEI and Pin error.
        /// </summary>
        internal static string IMEIAndPinError {
            get {
                return ResourceManager.GetString("IMEIAndPinError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à IMEI error.
        /// </summary>
        internal static string IMEIError {
            get {
                return ResourceManager.GetString("IMEIError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Input error.
        /// </summary>
        internal static string InputError {
            get {
                return ResourceManager.GetString("InputError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Insert alert error.
        /// </summary>
        internal static string InsertAlertErrorTitle {
            get {
                return ResourceManager.GetString("InsertAlertErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adding seekios failed.
        /// </summary>
        internal static string InsertSeekiosError {
            get {
                return ResourceManager.GetString("InsertSeekiosError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Located over 1 year ago.
        /// </summary>
        internal static string ListSeekios_LastPositionMoreThanOneYear {
            get {
                return ResourceManager.GetString("ListSeekios_LastPositionMoreThanOneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No location available.
        /// </summary>
        internal static string ListSeekios_LastPositionNone {
            get {
                return ResourceManager.GetString("ListSeekios_LastPositionNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Located {0}d at {1}.
        /// </summary>
        internal static string ListSeekios_LastPositionPlurial {
            get {
                return ResourceManager.GetString("ListSeekios_LastPositionPlurial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Located today at {0}.
        /// </summary>
        internal static string ListSeekios_LastPositionToday {
            get {
                return ResourceManager.GetString("ListSeekios_LastPositionToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yesterday at {0}.
        /// </summary>
        internal static string ListSeekios_LastPositionYesterday {
            get {
                return ResourceManager.GetString("ListSeekios_LastPositionYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application failed to refresh the data in background. If the problem persists, contact the technical team..
        /// </summary>
        internal static string LoadUserEnvironmentContent {
            get {
                return ResourceManager.GetString("LoadUserEnvironmentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to refresh data.
        /// </summary>
        internal static string LoadUserEnvironmentTitle {
            get {
                return ResourceManager.GetString("LoadUserEnvironmentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while retrieving locations.
        /// </summary>
        internal static string LocationsErrorTitle {
            get {
                return ResourceManager.GetString("LocationsErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error while retrieving dates.
        /// </summary>
        internal static string LowerAndUpperDateErrorTitle {
            get {
                return ResourceManager.GetString("LowerAndUpperDateErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot get lower date.
        /// </summary>
        internal static string LowerDateError {
            get {
                return ResourceManager.GetString("LowerDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The position of your seekios has been recovered.
        /// </summary>
        internal static string MapRefreshEnded {
            get {
                return ResourceManager.GetString("MapRefreshEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We could not recover the position of your seekios.
        /// </summary>
        internal static string MapRefreshFailed {
            get {
                return ResourceManager.GetString("MapRefreshFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to reactivate mode.
        /// </summary>
        internal static string Mode_unableToRestartModeDescr {
            get {
                return ResourceManager.GetString("Mode_unableToRestartModeDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unexpected error.
        /// </summary>
        internal static string Mode_unableToRestartModeTitle {
            get {
                return ResourceManager.GetString("Mode_unableToRestartModeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Activity.
        /// </summary>
        internal static string ModeActivity {
            get {
                return ResourceManager.GetString("ModeActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Border.
        /// </summary>
        internal static string ModeBorder {
            get {
                return ResourceManager.GetString("ModeBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Warning ! The seekios is in power saving so the mode will be active no later than the next noon. (The icon is gray, it will turn green when the mode will be active).
        /// </summary>
        internal static string ModeChangePowerSaving {
            get {
                return ResourceManager.GetString("ModeChangePowerSaving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Change mode ?.
        /// </summary>
        internal static string ModeChangeTitle {
            get {
                return ResourceManager.GetString("ModeChangeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Don&apos;t Move.
        /// </summary>
        internal static string ModeDontMove {
            get {
                return ResourceManager.GetString("ModeDontMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Follow Me.
        /// </summary>
        internal static string ModeFollowMe {
            get {
                return ResourceManager.GetString("ModeFollowMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The mode has not been configured.
        /// </summary>
        internal static string ModeNotConfigured {
            get {
                return ResourceManager.GetString("ModeNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error setting mode.
        /// </summary>
        internal static string ModeNotConfiguredTitle {
            get {
                return ResourceManager.GetString("ModeNotConfiguredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Road.
        /// </summary>
        internal static string ModeRoad {
            get {
                return ResourceManager.GetString("ModeRoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tracking.
        /// </summary>
        internal static string ModeTracking {
            get {
                return ResourceManager.GetString("ModeTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone.
        /// </summary>
        internal static string ModeZone {
            get {
                return ResourceManager.GetString("ModeZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zone points intersect. The area should remain green..
        /// </summary>
        internal static string ModeZone_NotValidZoneDescription {
            get {
                return ResourceManager.GetString("ModeZone_NotValidZoneDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Invalid area.
        /// </summary>
        internal static string ModeZone_NotValidZoneTitle {
            get {
                return ResourceManager.GetString("ModeZone_NotValidZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error occurred while deleting the seekios. Please try again later and if the problem persists, contact Technical Support..
        /// </summary>
        internal static string MySeekios_DeleteSeekios_Content {
            get {
                return ResourceManager.GetString("MySeekios_DeleteSeekios_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to delete.
        /// </summary>
        internal static string MySeekios_DeleteSeekios_Title {
            get {
                return ResourceManager.GetString("MySeekios_DeleteSeekios_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nous n&apos;avons pas réussi à récupérer vos anciennes positions. Quittez la carte puis revenez-y dessus. Si le problème persiste contactez nous à travers le feedback de l&apos;application..
        /// </summary>
        internal static string NoDataFromLocationByMode {
            get {
                return ResourceManager.GetString("NoDataFromLocationByMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string NoDataFromLocationByModeButton {
            get {
                return ResourceManager.GetString("NoDataFromLocationByModeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string NoInternetButton {
            get {
                return ResourceManager.GetString("NoInternetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must be connected to the internet to log out of the application..
        /// </summary>
        internal static string NoInternetDeconnection {
            get {
                return ResourceManager.GetString("NoInternetDeconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string NoInternetDeconnectionButton {
            get {
                return ResourceManager.GetString("NoInternetDeconnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application needs to be connected to the internet to perform this request..
        /// </summary>
        internal static string NoInternetMessage {
            get {
                return ResourceManager.GetString("NoInternetMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No internet.
        /// </summary>
        internal static string NoInternetTitle {
            get {
                return ResourceManager.GetString("NoInternetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No more credits left.
        /// </summary>
        internal static string NoMoreCredits {
            get {
                return ResourceManager.GetString("NoMoreCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seekios: {0}, low battery received {1}.
        /// </summary>
        internal static string NotificationCriticalBatteryContent {
            get {
                return ResourceManager.GetString("NotificationCriticalBatteryContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alert low battery !.
        /// </summary>
        internal static string NotificationCriticalBatteryTitle {
            get {
                return ResourceManager.GetString("NotificationCriticalBatteryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string NotificationErrorButtonClose {
            get {
                return ResourceManager.GetString("NotificationErrorButtonClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explanation.
        /// </summary>
        internal static string NotificationErrorButtonTuto {
            get {
                return ResourceManager.GetString("NotificationErrorButtonTuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to register for notifications. Attention, without notifications the application will not function correctly..
        /// </summary>
        internal static string NotificationErrorDescr {
            get {
                return ResourceManager.GetString("NotificationErrorDescr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error notification.
        /// </summary>
        internal static string NotificationErrorTitle {
            get {
                return ResourceManager.GetString("NotificationErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seekios: {0} displacement received {1} !.
        /// </summary>
        internal static string NotificationMovedContent {
            get {
                return ResourceManager.GetString("NotificationMovedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Has moved !.
        /// </summary>
        internal static string NotificationMovedTitle {
            get {
                return ResourceManager.GetString("NotificationMovedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seekios: {0} out of the zone received {1} !.
        /// </summary>
        internal static string NotificationOutOfZoneContent {
            get {
                return ResourceManager.GetString("NotificationOutOfZoneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Out of zone !.
        /// </summary>
        internal static string NotificationOutOfZoneTitle {
            get {
                return ResourceManager.GetString("NotificationOutOfZoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seekios: {0}, deactivation received {1}.
        /// </summary>
        internal static string NotificationPowerSavingContent {
            get {
                return ResourceManager.GetString("NotificationPowerSavingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Power saving disabled !.
        /// </summary>
        internal static string NotificationPowerSavingTitle {
            get {
                return ResourceManager.GetString("NotificationPowerSavingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changing your notification preferences failed. Please try again and if the problem persists, contact Technical Support..
        /// </summary>
        internal static string NotificationSettingErrorContent {
            get {
                return ResourceManager.GetString("NotificationSettingErrorContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Server error.
        /// </summary>
        internal static string NotificationSettingErrorTitle {
            get {
                return ResourceManager.GetString("NotificationSettingErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seekios: {0}, SOS received {1}.
        /// </summary>
        internal static string NotificationSOSAlertContent {
            get {
                return ResourceManager.GetString("NotificationSOSAlertContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alert SOS received !.
        /// </summary>
        internal static string NotificationSOSAlertTitle {
            get {
                return ResourceManager.GetString("NotificationSOSAlertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à seekios: {0}, position received {1}.
        /// </summary>
        internal static string NotificationSOSPositionContent {
            get {
                return ResourceManager.GetString("NotificationSOSPositionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SOS position received !.
        /// </summary>
        internal static string NotificationSOSPositionTitle {
            get {
                return ResourceManager.GetString("NotificationSOSPositionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Impossible to retrieve the firmware version.
        /// </summary>
        internal static string NoVersionEmbedded {
            get {
                return ResourceManager.GetString("NoVersionEmbedded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem with on our webservices has occurred. Contact us through the feedback of the application if it&apos;s happen again..
        /// </summary>
        internal static string NoWebserviceDeconnection {
            get {
                return ResourceManager.GetString("NoWebserviceDeconnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string NoWebserviceDeconnectionButton {
            get {
                return ResourceManager.GetString("NoWebserviceDeconnectionButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Refresh your seekios {0} failed. Your seekios is either switched off or in an area not covered by the network 2G..
        /// </summary>
        internal static string OnDemandMessageFailedBody {
            get {
                return ResourceManager.GetString("OnDemandMessageFailedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No position found.
        /// </summary>
        internal static string OnDemandMessageFailedTitle {
            get {
                return ResourceManager.GetString("OnDemandMessageFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There are {3} days at {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string OneDayDateTime {
            get {
                return ResourceManager.GetString("OneDayDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {3} days at {0:00}:{1:00}.
        /// </summary>
        internal static string OneDayDateTimeNoSeconds {
            get {
                return ResourceManager.GetString("OneDayDateTimeNoSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à One of the fields is empty.
        /// </summary>
        internal static string ParameterActivity_FieldEmpty {
            get {
                return ResourceManager.GetString("ParameterActivity_FieldEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Empty field(s).
        /// </summary>
        internal static string ParameterActivity_FieldEmptyTitle {
            get {
                return ResourceManager.GetString("ParameterActivity_FieldEmptyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à New passwords do not match.
        /// </summary>
        internal static string PasswordDoesntMatch {
            get {
                return ResourceManager.GetString("PasswordDoesntMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Incorrect passwords.
        /// </summary>
        internal static string PasswordDoesntMatchTitle {
            get {
                return ResourceManager.GetString("PasswordDoesntMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password error.
        /// </summary>
        internal static string PasswordError {
            get {
                return ResourceManager.GetString("PasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password too short.
        /// </summary>
        internal static string PasswordTooShort {
            get {
                return ResourceManager.GetString("PasswordTooShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your password has been updated.
        /// </summary>
        internal static string PasswordUpdated {
            get {
                return ResourceManager.GetString("PasswordUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to update your password.
        /// </summary>
        internal static string PasswordUpdateFailed {
            get {
                return ResourceManager.GetString("PasswordUpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password update.
        /// </summary>
        internal static string PasswordUpdateTitle {
            get {
                return ResourceManager.GetString("PasswordUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You can not perform this action because your seekios is in energy saving..
        /// </summary>
        internal static string PowerSavingOn {
            get {
                return ResourceManager.GetString("PowerSavingOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Power saving activated.
        /// </summary>
        internal static string PowerSavingOnTitle {
            get {
                return ResourceManager.GetString("PowerSavingOnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Explanation.
        /// </summary>
        internal static string PowerSavingTuto {
            get {
                return ResourceManager.GetString("PowerSavingTuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You must define at least one SOS recipient.
        /// </summary>
        internal static string RecipientListNeeded {
            get {
                return ResourceManager.GetString("RecipientListNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yes, every {0}.
        /// </summary>
        internal static string RefreshRate {
            get {
                return ResourceManager.GetString("RefreshRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application failed to communicate with the seekios.
        /// </summary>
        internal static string RefreshSeekiosFailed {
            get {
                return ResourceManager.GetString("RefreshSeekiosFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to locate your seekios.
        /// </summary>
        internal static string RefreshSeekiosFailedTitle {
            get {
                return ResourceManager.GetString("RefreshSeekiosFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Every 16th of the month you get a 60 credits refund by seekios :) Locate well..
        /// </summary>
        internal static string RelaodCreditMonthlyContent {
            get {
                return ResourceManager.GetString("RelaodCreditMonthlyContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Your credit recharge has arrived!.
        /// </summary>
        internal static string RelaodCreditMonthlyTitle {
            get {
                return ResourceManager.GetString("RelaodCreditMonthlyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An email has been sent to you to reset your password..
        /// </summary>
        internal static string ResetPasswordRequestSentText {
            get {
                return ResourceManager.GetString("ResetPasswordRequestSentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email sent.
        /// </summary>
        internal static string ResetPasswordRequestSentTitle {
            get {
                return ResourceManager.GetString("ResetPasswordRequestSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Enter a name for your seekios.
        /// </summary>
        internal static string SeekiosNameEmpty {
            get {
                return ResourceManager.GetString("SeekiosNameEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Seekios unavailable.
        /// </summary>
        internal static string SeekiosUnavailable {
            get {
                return ResourceManager.GetString("SeekiosUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application failed to connect to SignalR. If the problem persists, contact the technical team..
        /// </summary>
        internal static string SignalRNotSubscribeContent {
            get {
                return ResourceManager.GetString("SignalRNotSubscribeContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unreachable real time system.
        /// </summary>
        internal static string SignalRNotSubscribeTitle {
            get {
                return ResourceManager.GetString("SignalRNotSubscribeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Something went wrong while communicating with your seekios.
        /// </summary>
        internal static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SOS Alert {0}d at {1}.
        /// </summary>
        internal static string SOSAlertSinceAt {
            get {
                return ResourceManager.GetString("SOSAlertSinceAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SOS Alert at {0}.
        /// </summary>
        internal static string SOSAlertTodayAt {
            get {
                return ResourceManager.GetString("SOSAlertTodayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à SOS Alert yesterday at {0}.
        /// </summary>
        internal static string SOSAlertYesterdayAt {
            get {
                return ResourceManager.GetString("SOSAlertYesterdayAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A TimeOut error occurred. This error is often due to poor network quality of the device. Try again and if the problem persists, contact the technical support of seekios..
        /// </summary>
        internal static string TimeoutError {
            get {
                return ResourceManager.GetString("TimeoutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The request failed.
        /// </summary>
        internal static string TimeoutErrorTitle {
            get {
                return ResourceManager.GetString("TimeoutErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Today at {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string TodayDateTime {
            get {
                return ResourceManager.GetString("TodayDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Today at {0:00}:{1:00}.
        /// </summary>
        internal static string TodayDateTimeNoSeconds {
            get {
                return ResourceManager.GetString("TodayDateTimeNoSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à There is no location to display.
        /// </summary>
        internal static string Tracking_noLocation {
            get {
                return ResourceManager.GetString("Tracking_noLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized access, token issue.
        /// </summary>
        internal static string UnauthorizedAccess {
            get {
                return ResourceManager.GetString("UnauthorizedAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unauthorized access.
        /// </summary>
        internal static string UnauthorizedAccessTitle {
            get {
                return ResourceManager.GetString("UnauthorizedAccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An HTTP error occurred. Try again and if the problem persists, contact the technical support of seekios..
        /// </summary>
        internal static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The request failed.
        /// </summary>
        internal static string UnexpectedErrorTitle {
            get {
                return ResourceManager.GetString("UnexpectedErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Update error.
        /// </summary>
        internal static string UpdateUserError {
            get {
                return ResourceManager.GetString("UpdateUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not update your account.
        /// </summary>
        internal static string UpdateUserFailed {
            get {
                return ResourceManager.GetString("UpdateUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A problem occurred while updating the user information. Please try again and if the problem persists, contact the technical support..
        /// </summary>
        internal static string UpdateUserFailedContent {
            get {
                return ResourceManager.GetString("UpdateUserFailedContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Query failed.
        /// </summary>
        internal static string UpdateUserFailedTitle {
            get {
                return ResourceManager.GetString("UpdateUserFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unable to update zone.
        /// </summary>
        internal static string UpdateZoneFailed {
            get {
                return ResourceManager.GetString("UpdateZoneFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Failed to update.
        /// </summary>
        internal static string UpdateZoneFailedTitle {
            get {
                return ResourceManager.GetString("UpdateZoneFailedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cannot get upper date.
        /// </summary>
        internal static string UpperDateError {
            get {
                return ResourceManager.GetString("UpperDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à You do not have enough credits to complete this action.
        /// </summary>
        internal static string UserNoRequestLeft {
            get {
                return ResourceManager.GetString("UserNoRequestLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No more credits.
        /// </summary>
        internal static string UserNoRequestLeftTitle {
            get {
                return ResourceManager.GetString("UserNoRequestLeftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The account linked to this email has not been validated. Log in to your mailbox and click on the account validation links..
        /// </summary>
        internal static string UserNotValidateText {
            get {
                return ResourceManager.GetString("UserNotValidateText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Account not validated.
        /// </summary>
        internal static string UserNotValidateTitle {
            get {
                return ResourceManager.GetString("UserNotValidateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The application fails to access the Internet.
        /// </summary>
        internal static string WebError {
            get {
                return ResourceManager.GetString("WebError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string WebErrorButtonText {
            get {
                return ResourceManager.GetString("WebErrorButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à An error has occurred.
        /// </summary>
        internal static string WebErrorTitle {
            get {
                return ResourceManager.GetString("WebErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Problem encountered while loading the language chosen.
        /// </summary>
        internal static string WrongLanguage {
            get {
                return ResourceManager.GetString("WrongLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Language error.
        /// </summary>
        internal static string WrongLanguageTitle {
            get {
                return ResourceManager.GetString("WrongLanguageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yesterday at {0:00}:{1:00}:{2:00}.
        /// </summary>
        internal static string YesterdayDateTime {
            get {
                return ResourceManager.GetString("YesterdayDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Yesterday at {0:00}:{1:00}.
        /// </summary>
        internal static string YesterdayDateTimeNoSeconds {
            get {
                return ResourceManager.GetString("YesterdayDateTimeNoSeconds", resourceCulture);
            }
        }
    }
}
